# Site settings
title: Cryptic Chat
email: dolphin@likethemammal.com
description: >
  We are a group of developers involved in the tech industry that work,
  laugh, discover, and grow together. We encourage each other to push the
  boundaries of the technology we work with everyday. To help reach our
  personal goals we collaborate often and want others to share in this 
  experience.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://cryptic.io" # the base hostname & protocol for your site
permalink: :title/
paginate: 13

author: "Chris Dolphin"
keywords: 'developers, dev blog, tech industry, programming, development'

# Build settings
markdown: redcarpet
